### ISSUE TITLE
Can’t use in Node.js

### ISSUE THREAD

**Issue by ai** [oleksandr-dukhovnyy/purify-html#2]
**Describe the bug**

Node.js and bundler exports are not equal.

In Node.js `purify-html` exports `{ default, setParser }`:

```js
import PurifyHTML from 'purify-html'
console.log(PurifyHTML) //=> { default, setParser }

let Purifier = PurifyHTML.default
let sanitizer = new Purifier()
sanitizer.sanitize(html) // works
```

But in Vite default export will contain `PurifyHTML` constructor:

```js
console.log(PurifyHTML) //=> class u { constructor(e2) }
```

**To Reproduce**

Run this code in Node.js

```js
// set-dom-parser.js
import { JSDOM } from 'jsdom'

global.window = new JSDOM().window
global.DOMParser = global.window.DOMParser
global.self = global.window.self
```

```js
import 'set-dom-parser.js'

import PurifyHTML from 'purify-html'
console.log(PurifyHTML)
```

**Expected behavior**

To works in Node.js with the same code as with bundler.

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox
- Version: 121

**Comment by ai** [comment]
Also, it will be nice to remove `globalThis.self` requirement. Right now JS bundle contain this variable but don’t use for some speific needs.

**Comment by ai** [comment]
One of possible solution is to not bundle JS files for Node.js, just compile TS to JS.

**Comment by oleksandr-dukhovnyy** [comment]
Thanks for bringing up this issue! Your feedback is valuable.

Expect the fix in the upcoming update (version **1.5.4**), scheduled for today by 9 PM (UTC+0).

**Comment by oleksandr-dukhovnyy** [comment]
@ai

Given the challenges of configuring webpack for builds (using 2 configuration files :/), I decided to transition the build process to Vite.

This allowed for a reduction in the amount of "boilerplate" code, retaining only the code that is truly necessary for functionality.

Now, your usage example can be streamlined to:

```js
// ~/set-dom-parser.js
import { JSDOM } from 'jsdom';

global.DOMParser = new JSDOM().window.DOMParser;
```

```js
// ~/main.js

import './set-dom-parser.js';
import PurifyHTML from 'purify-html';

const sanitizer = new PurifyHTML();

console.log(sanitizer.sanitize('<div>1</div>')); // '1'
```

Certainly, now exports in Vite and Node work as stated.

Available in version `1.5.4`.

**Comment by oleksandr-dukhovnyy** [comment]
https://github.com/oleksandr-dukhovnyy/purify-html/releases/tag/1.5.4

**Comment by ai** [comment]
Thanks for fast release.

**Comment by oleksandr-dukhovnyy** [comment]
Thanks for issue 🚀
